#ifndef KEYBOARD_TYPES_H
#define KEYBOARD_TYPES_H

#include <stdint.h>

typedef enum
{
    KEYBOARD_INVALID,
    KEYBOARD_PRESSED,
    KEYBOARD_RELEASED
} keyboard_event_type_t;


typedef enum
{
    KEYBOARD_KEYCODE_INVALID,

    /* first row */
    KEYBOARD_KEYCODE_ESC,
    KEYBOARD_KEYCODE_F1,
    KEYBOARD_KEYCODE_F2,
    KEYBOARD_KEYCODE_F3,
    KEYBOARD_KEYCODE_F4,
    KEYBOARD_KEYCODE_F5,
    KEYBOARD_KEYCODE_F6,
    KEYBOARD_KEYCODE_F7,
    KEYBOARD_KEYCODE_F8,
    KEYBOARD_KEYCODE_F9,
    KEYBOARD_KEYCODE_F10,
    KEYBOARD_KEYCODE_F11,
    KEYBOARD_KEYCODE_F12,
    KEYBOARD_KEYCODE_PRINT_SCREEN,
    KEYBOARD_KEYCODE_SCROLL_LOCK,
    KEYBOARD_KEYCODE_PAUSE,


    /* second row */
    KEYBOARD_KEYCODE_BACK_TICK,
    KEYBOARD_KEYCODE_1,
    KEYBOARD_KEYCODE_2,
    KEYBOARD_KEYCODE_3,
    KEYBOARD_KEYCODE_4,
    KEYBOARD_KEYCODE_5,
    KEYBOARD_KEYCODE_6,
    KEYBOARD_KEYCODE_7,
    KEYBOARD_KEYCODE_8,
    KEYBOARD_KEYCODE_9,
    KEYBOARD_KEYCODE_0,
    KEYBOARD_KEYCODE_HYPHEN,
    KEYBOARD_KEYCODE_EQUALS,
    KEYBOARD_KEYCODE_BACKSPACE,
    KEYBOARD_KEYCODE_INSERT,
    KEYBOARD_KEYCODE_HOME,
    KEYBOARD_KEYCODE_PAGE_UP,


    /* third row */
    KEYBOARD_KEYCODE_TAB,
    KEYBOARD_KEYCODE_Q,
    KEYBOARD_KEYCODE_W,
    KEYBOARD_KEYCODE_E,
    KEYBOARD_KEYCODE_R,
    KEYBOARD_KEYCODE_T,
    KEYBOARD_KEYCODE_Y,
    KEYBOARD_KEYCODE_U,
    KEYBOARD_KEYCODE_I,
    KEYBOARD_KEYCODE_O,
    KEYBOARD_KEYCODE_P,
    KEYBOARD_KEYCODE_BRACKET_L,
    KEYBOARD_KEYCODE_BRACKET_R,
    KEYBOARD_KEYCODE_BACKSLASH,
    KEYBOARD_KEYCODE_DELETE,
    KEYBOARD_KEYCODE_END,
    KEYBOARD_KEYCODE_PAGE_DOWN,


    /* fourth row */
    KEYBOARD_KEYCODE_CAPS_LOCK,
    KEYBOARD_KEYCODE_A,
    KEYBOARD_KEYCODE_S,
    KEYBOARD_KEYCODE_D,
    KEYBOARD_KEYCODE_F,
    KEYBOARD_KEYCODE_G,
    KEYBOARD_KEYCODE_H,
    KEYBOARD_KEYCODE_J,
    KEYBOARD_KEYCODE_K,
    KEYBOARD_KEYCODE_L,
    KEYBOARD_KEYCODE_SEMICOLON,
    KEYBOARD_KEYCODE_SINGLE_QUOTE,
    KEYBOARD_KEYCODE_ENTER,


    /* fifth row */
    KEYBOARD_KEYCODE_SHIFT_L,
    KEYBOARD_KEYCODE_ISO_BACKSLASH,
    KEYBOARD_KEYCODE_Z,
    KEYBOARD_KEYCODE_X,
    KEYBOARD_KEYCODE_C,
    KEYBOARD_KEYCODE_V,
    KEYBOARD_KEYCODE_B,
    KEYBOARD_KEYCODE_N,
    KEYBOARD_KEYCODE_M,
    KEYBOARD_KEYCODE_COMMA,
    KEYBOARD_KEYCODE_DOT,
    KEYBOARD_KEYCODE_SLASH,
    KEYBOARD_KEYCODE_SHIFT_R,
    KEYBOARD_KEYCODE_ARROW_UP,

    /* sixth row */
    KEYBOARD_KEYCODE_APPLE_FN,
    KEYBOARD_KEYCODE_CONTROL_L,
    KEYBOARD_KEYCODE_SUPER_L,
    KEYBOARD_KEYCODE_ALT_L,
    KEYBOARD_KEYCODE_SPACE,
    KEYBOARD_KEYCODE_ALT_R,
    KEYBOARD_KEYCODE_SUPER_R,
    KEYBOARD_KEYCODE_PC_MENU,
    KEYBOARD_KEYCODE_CONTROL_R,
    KEYBOARD_KEYCODE_ARROW_LEFT,
    KEYBOARD_KEYCODE_ARROW_DOWN,
    KEYBOARD_KEYCODE_ARROW_RIGHT,

    /* KEYPAD */
    KEYBOARD_KEYCODE_KEYPAD_ASTRIX,
    KEYBOARD_KEYCODE_KEYPAD_7,
    KEYBOARD_KEYCODE_KEYPAD_8,
    KEYBOARD_KEYCODE_KEYPAD_9,
    KEYBOARD_KEYCODE_KEYPAD_HYPHEN,
    KEYBOARD_KEYCODE_KEYPAD_4,
    KEYBOARD_KEYCODE_KEYPAD_5,
    KEYBOARD_KEYCODE_KEYPAD_6,
    KEYBOARD_KEYCODE_KEYPAD_PLUS,
    KEYBOARD_KEYCODE_KEYPAD_1,
    KEYBOARD_KEYCODE_KEYPAD_2,
    KEYBOARD_KEYCODE_KEYPAD_3,
    KEYBOARD_KEYCODE_KEYPAD_0,
    KEYBOARD_KEYCODE_KEYPAD_DOT,

    /* MISC */
    KEYBOARD_KEYCODE_MISC_NUM_LOCK,



    KEYBOARD_KEYCODE_COUNT
} keyboard_keycode_t;


typedef struct
{
    keyboard_event_type_t event_type;
    keyboard_keycode_t keycode;
} keyboard_event_t;


#endif /* KEYBOARD_TYPES_H */
