#ifndef KEYBOARD_DRIVER_TYPES_H
#define KEYBOARD_DRIVER_TYPES_H

#include <stdint.h>
typedef enum
{
    KEYBOARD_INVALID,
    KEYBOARD_PRESSED,
    KEYBOARD_RELEASED
} keyboard_event_type_t;


typedef enum
{
    /* first row */
    KEYBOARD_DRIVER_KEYCODE_ESC,
    KEYBOARD_DRIVER_KEYCODE_F1,
    KEYBOARD_DRIVER_KEYCODE_F2,
    KEYBOARD_DRIVER_KEYCODE_F3,
    KEYBOARD_DRIVER_KEYCODE_F4,
    KEYBOARD_DRIVER_KEYCODE_F5,
    KEYBOARD_DRIVER_KEYCODE_F6,
    KEYBOARD_DRIVER_KEYCODE_F7,
    KEYBOARD_DRIVER_KEYCODE_F8,
    KEYBOARD_DRIVER_KEYCODE_F9,
    KEYBOARD_DRIVER_KEYCODE_F10,
    KEYBOARD_DRIVER_KEYCODE_F11,
    KEYBOARD_DRIVER_KEYCODE_F12,
    KEYBOARD_DRIVER_KEYCODE_PRINT_SCREEN,
    KEYBOARD_DRIVER_KEYCODE_SCROLL_LOCK,
    KEYBOARD_DRIVER_KEYCODE_PAUSE,


    /* second row */
    KEYBOARD_DRIVER_KEYCODE_TILDE,
    KEYBOARD_DRIVER_KEYCODE_1,
    KEYBOARD_DRIVER_KEYCODE_2,
    KEYBOARD_DRIVER_KEYCODE_3,
    KEYBOARD_DRIVER_KEYCODE_4,
    KEYBOARD_DRIVER_KEYCODE_5,
    KEYBOARD_DRIVER_KEYCODE_6,
    KEYBOARD_DRIVER_KEYCODE_7,
    KEYBOARD_DRIVER_KEYCODE_8,
    KEYBOARD_DRIVER_KEYCODE_9,
    KEYBOARD_DRIVER_KEYCODE_0,
    KEYBOARD_DRIVER_KEYCODE_HYPHEN,
    KEYBOARD_DRIVER_KEYCODE_EQUALS,
    KEYBOARD_DRIVER_KEYCODE_BACKSPACE,
    KEYBOARD_DRIVER_KEYCODE_INSERT,
    KEYBOARD_DRIVER_KEYCODE_HOME,
    KEYBOARD_DRIVER_KEYCODE_PAGE_UP,


    /* third row */
    KEYBOARD_DRIVER_KEYCODE_TAB,
    KEYBOARD_DRIVER_KEYCODE_Q,
    KEYBOARD_DRIVER_KEYCODE_W,
    KEYBOARD_DRIVER_KEYCODE_E,
    KEYBOARD_DRIVER_KEYCODE_R,
    KEYBOARD_DRIVER_KEYCODE_T,
    KEYBOARD_DRIVER_KEYCODE_Y,
    KEYBOARD_DRIVER_KEYCODE_U,
    KEYBOARD_DRIVER_KEYCODE_I,
    KEYBOARD_DRIVER_KEYCODE_O,
    KEYBOARD_DRIVER_KEYCODE_P,
    KEYBOARD_DRIVER_KEYCODE_BRACKET_L,
    KEYBOARD_DRIVER_KEYCODE_BRACKET_R,
    KEYBOARD_DRIVER_KEYCODE_BACKSLASH,
    KEYBOARD_DRIVER_KEYCODE_DELETE,
    KEYBOARD_DRIVER_KEYCODE_END,
    KEYBOARD_DRIVER_KEYCODE_PAGE_DOWN,


    /* fourth row */
    KEYBOARD_DRIVER_KEYCODE_CAPS_LOCK,
    KEYBOARD_DRIVER_KEYCODE_A,
    KEYBOARD_DRIVER_KEYCODE_S,
    KEYBOARD_DRIVER_KEYCODE_D,
    KEYBOARD_DRIVER_KEYCODE_F,
    KEYBOARD_DRIVER_KEYCODE_G,
    KEYBOARD_DRIVER_KEYCODE_H,
    KEYBOARD_DRIVER_KEYCODE_J,
    KEYBOARD_DRIVER_KEYCODE_K,
    KEYBOARD_DRIVER_KEYCODE_L,
    KEYBOARD_DRIVER_KEYCODE_SEMI_COLON,
    KEYBOARD_DRIVER_KEYCODE_SINGLE_QUOTE,
    KEYBOARD_DRIVER_KEYCODE_ENTER,


    /* fifth row */
    KEYBOARD_DRIVER_KEYCODE_SHIFT_L,
    KEYBOARD_DRIVER_KEYCODE_ISO_BACKSLASH,
    KEYBOARD_DRIVER_KEYCODE_Z,
    KEYBOARD_DRIVER_KEYCODE_X,
    KEYBOARD_DRIVER_KEYCODE_C,
    KEYBOARD_DRIVER_KEYCODE_V,
    KEYBOARD_DRIVER_KEYCODE_B,
    KEYBOARD_DRIVER_KEYCODE_N,
    KEYBOARD_DRIVER_KEYCODE_M,
    KEYBOARD_DRIVER_KEYCODE_COMMA,
    KEYBOARD_DRIVER_KEYCODE_DOT,
    KEYBOARD_DRIVER_KEYCODE_SLASH,
    KEYBOARD_DRIVER_KEYCODE_SHIFT_R,
    KEYBOARD_DRIVER_KEYCODE_ARROW_UP,

    /* sixth row */
    KEYBOARD_DRIVER_KEYCODE_APPLE_FN,
    KEYBOARD_DRIVER_KEYCODE_CONTROL_L,
    KEYBOARD_DRIVER_KEYCODE_SUPER_L,
    KEYBOARD_DRIVER_KEYCODE_ALT_L,
    KEYBOARD_DRIVER_KEYCODE_SPACE,
    KEYBOARD_DRIVER_KEYCODE_ALT_R,
    KEYBOARD_DRIVER_KEYCODE_SUPER_R,
    KEYBOARD_DRIVER_KEYCODE_PC_MENU,
    KEYBOARD_DRIVER_KEYCODE_CONTROL_R,
    KEYBOARD_DRIVER_KEYCODE_ARROW_LEFT,
    KEYBOARD_DRIVER_KEYCODE_ARROW_DOWN,
    KEYBOARD_DRIVER_KEYCODE_ARROW_RIGHT,
} keyboard_driver_keycode_t;


typedef struct
{
    keyboard_event_type_t event_type;
    char key_ascii;
} keyboard_event_t;


#endif /* KEYBOARD_DRIVER_TYPES_H */
