#include <ata_driver.h>
#include <console_output.h>

#define ATA_DRIVER_IO_OFFSET_PRIMARY 0x1F0
#define ATA_DRIVER_CONTROL_OFFSET_PRIMARY 0x3F6

#define ATA_DRIVER_IO_OFFSET_SECONDARY 0x170
#define ATA_DRIVER_CONTROL_OFFSET_SECONDARY 0x376

#define ATA_DRIVER_IO_DATA_PRIMARY                  ((ATA_DRIVER_BUS_OFFSET_IO_PRIMARY))
#define ATA_DRIVER_IO_ERROR_PRIMARY                 ((ATA_DRIVER_BUS_OFFSET_IO_PRIMARY) + 1)
#define ATA_DRIVER_IO_FEATURES_PRIMARY              ((ATA_DRIVER_BUS_OFFSET_IO_PRIMARY) + 1)
#define ATA_DRIVER_IO_SECTOR_COUNT_PRIMARY          ((ATA_DRIVER_BUS_OFFSET_IO_PRIMARY) + 2)
#define ATA_DRIVER_IO_SECTOR_LBA_LOW_PRIMARY        ((ATA_DRIVER_BUS_OFFSET_IO_PRIMARY) + 3)
#define ATA_DRIVER_IO_SECTOR_LBA_MID_PRIMARY        ((ATA_DRIVER_BUS_OFFSET_IO_PRIMARY) + 4)
#define ATA_DRIVER_IO_SECTOR_LBA_HIGH_PRIMARY       ((ATA_DRIVER_BUS_OFFSET_IO_PRIMARY) + 5)
#define ATA_DRIVER_IO_SECTOR_DRIVE_HEAD_PRIMARY     ((ATA_DRIVER_BUS_OFFSET_IO_PRIMARY) + 6)
#define ATA_DRIVER_IO_SECTOR_STATUS_PRIMARY         ((ATA_DRIVER_BUS_OFFSET_IO_PRIMARY) + 7)
#define ATA_DRIVER_IO_SECTOR_COMMAND_PRIMARY        ((ATA_DRIVER_BUS_OFFSET_IO_PRIMARY) + 7)

#define ATA_DRIVER_CONTROL_ALTERNATE_STATUS_PRIMARY ((ATA_DRIVER_CONTROL_OFFSET_PRIMARY) + 0)
#define ATA_DRIVER_CONTROL_DEVICE_CONTROL_PRIMARY   ((ATA_DRIVER_CONTROL_OFFSET_PRIMARY) + 0)
#define ATA_DRIVER_CONTROL_DRIVE_ADDRESS_PRIMARY    ((ATA_DRIVER_CONTROL_OFFSET_PRIMARY) + 1)


#define ATA_DRIVER_IO_DATA_SECONDARY                  ((ATA_DRIVER_BUS_OFFSET_IO_SECONDARY))
#define ATA_DRIVER_IO_ERROR_SECONDARY                 ((ATA_DRIVER_BUS_OFFSET_IO_SECONDARY) + 1)
#define ATA_DRIVER_IO_FEATURES_SECONDARY              ((ATA_DRIVER_BUS_OFFSET_IO_SECONDARY) + 1)
#define ATA_DRIVER_IO_SECTOR_COUNT_SECONDARY          ((ATA_DRIVER_BUS_OFFSET_IO_SECONDARY) + 2)
#define ATA_DRIVER_IO_SECTOR_LBA_LOW_SECONDARY        ((ATA_DRIVER_BUS_OFFSET_IO_SECONDARY) + 3)
#define ATA_DRIVER_IO_SECTOR_LBA_MID_SECONDARY        ((ATA_DRIVER_BUS_OFFSET_IO_SECONDARY) + 4)
#define ATA_DRIVER_IO_SECTOR_LBA_HIGH_SECONDARY       ((ATA_DRIVER_BUS_OFFSET_IO_SECONDARY) + 5)
#define ATA_DRIVER_IO_SECTOR_DRIVE_HEAD_SECONDARY     ((ATA_DRIVER_BUS_OFFSET_IO_SECONDARY) + 6)
#define ATA_DRIVER_IO_SECTOR_STATUS_SECONDARY         ((ATA_DRIVER_BUS_OFFSET_IO_SECONDARY) + 7)
#define ATA_DRIVER_IO_SECTOR_COMMAND_SECONDARY        ((ATA_DRIVER_BUS_OFFSET_IO_SECONDARY) + 7)

#define ATA_DRIVER_CONTROL_ALTERNATE_STATUS_SECONDARY ((ATA_DRIVER_CONTROL_OFFSET_SECONDARY) + 0)
#define ATA_DRIVER_CONTROL_DEVICE_CONTROL_SECONDARY   ((ATA_DRIVER_CONTROL_OFFSET_SECONDARY) + 0)
#define ATA_DRIVER_CONTROL_DRIVE_ADDRESS_SECONDARY    ((ATA_DRIVER_CONTROL_OFFSET_SECONDARY) + 1)

void ata_driver_setup(void)
{
    console_output_printf("Preparing ata_driver\n");
}
